import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeController from "@/components/ThemeController";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hexleap Frontend Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeController>
      <html lang="en" className="overflow-x-hidden">
        <body className={`${inter.className} relative overflow-x-hidden w-screen dark:bg-[#292b32] dark:text-white`}>{children}</body>
      </html>
    </ThemeController>
  );
}
