import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hexleap Frontend Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="h-screen dark:bg-[#292b32] dark:text-white">{children}</body>
    </html>
  );
}
